In [1]:
import tensorflow as tf
import ssl

In [6]:
ssl._create_default_https_context = ssl._create_unverified_context
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()


x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.sigmoid),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

#model.fit(x_train, y_train, epochs=1)
#model.evaluate(x_test, y_test)

In [ ]:
model.evaluate(x_test, y_test)

In [ ]:
y_train

In [ ]:
x_train.shape

In [ ]:
size = 512

In [ ]:
import tensorflow as tf
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
input_size = [28, 28]

In [ ]:
    network = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=input_size),
    tf.keras.layers.Dense(size, activation=activation),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(output_size, activation=output_activation)
    ])

In [10]:
input_layer = tf.reshape(x_train, [-1, 28, 28, 1])

In [26]:
#hidden = tf.keras.layers.Dense(inputs=input_layer, units=size, activation=activation)
hidden = tf.layers.dense(inputs=input_layer, units=size, activation=tf.nn.relu)

In [27]:
for i in range(0, 5):
    print(i)

0
1
2
3
4


In [9]:
x = tf.constant([[1,2,3,4]], dtype=tf.float32)
inputs = tf.layers.dense(inputs=x, units=size, activation=None)

mean, variance = tf.nn.moments(x, [1])
with tf.Session() as sess:
    m, v = sess.run([mean, variance])
    print(m, v)

[2.5] [1.25]


In [10]:
ten = tf.constant([[0.3,0.2,0.5,0.6]], dtype=tf.float32)

In [11]:
#squares = tf.map_fn(lambda x: log x, ten)
logged = tf.math.log(ten)
end = tf.reduce_sum(logged)

with tf.Session() as sess:
    sq = sess.run(logged)
    print(sq)

end = tf.reduce_sum(logged)

with tf.Session() as sess:
    sq = sess.run(end)
    print(sq)

NameError: name 'ten' is not defined

In [12]:
tf.reset_default_graph()

#define a new activation function which do the mean
x = tf.constant([[1,2,3,4]], dtype=tf.float32)
inputs = tf.placeholder(shape=[None], name="in", dtype=tf.float32)

with tf.variable_scope("test"):
    inputs = tf.layers.dense(inputs=x, units=4, activation=None)
    logstd = tf.get_variable("dummy_var", shape=[4], trainable=True)
    z = tf.random_normal(tf.shape(inputs), mean=0.0, stddev=1.0)
    sy_std = tf.exp(logstd)
    sy_sampled_ac = inputs + sy_std * z

In [13]:
session = tf.Session()
init = tf.initialize_all_variables()
session.run(init)
sy = session.run(inputs)
print(sy)

[[-2.3331637  3.721153   1.8875959 -1.9066582]]


In [14]:
print(session.run(sy_std))

[0.47525772 1.475485   1.9133694  1.3350419 ]


In [15]:
print(session.run(sy_sampled_ac))

[[-2.7498388  5.741282   2.3425262 -1.2266047]]


In [16]:
log = session.run(logstd)
print(log)

[-0.74389803  0.38898677  0.64886576  0.28896266]


In [ ]:
q_n = tf.placeholder(shape=[None], name="qn", dtype=tf.float32)